config/routes.rb
Rails.application.routes.draw do
 
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :categories
  resources :books
  devise_for :users
  #devise_for :users, :controllers => {:registrations => 'user/registrations' }

  root 'books#index'

  get 'explore' => 'books#explore'

  get 'about' => 'books#about'
  get 'contact_us' => 'books#contact_us', path: 'contact-us'

  #get 'users/:id' => 'users#show'
  get 'abc/:id' => 'users#show'

end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :book_categories
  has_many :categories, through: :book_categories
  
  has_attached_file :book_cover, styles: { medium: "400x400>"}, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :book_cover, content_type: /\Aimage\/.*\z/

  

end

app/models/book_category.rb
class BookCategory < ApplicationRecord
	belongs_to :book
	belongs_to :category
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :book_categories
	has_many :books, through: :book_categories
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable  
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :books       

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception



  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end
  
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]


  def explore
    @books = Book.all
  end

  def about
  end

  def contact_us
  end

  # GET /books
  # GET /books.json
  def index    
    @books = Book.all
    @featured_books = Book.all    
    @books = Book.paginate(:page => params[:page], :per_page => 10)
    render :layout => 'home'
  end

  # GET /books/1
  # GET /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:name, :author, :price, :book_cover, category_ids: [])
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
        @category = Category.find(params[:id])
        @category_books = @category.books.paginate(page: params[:page], per_page: 10)
        #@category_articles = @category.articles
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	#attr_accessible :username

	def show
		@user = User.find(params[:id])
		@user_books = @user.books.paginate(page: params[:page], per_page: 5)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def gravatar_for(user, options = { size: 80})
	    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
	    size = options[:size]
	    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
	    image_tag(gravatar_url, alt: user.username, class: "img-circle")
	end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_book.html.erb
<% obj.each_slice(4) do |slice| %>
  <div class="row books_row">
  <% slice.each do |book| %>
    <div class="col-md-3 book"> 
      <%= link_to book_path(book) do %> 
          <div class="cover">
            <%= image_tag book.book_cover %>
          </div>          
          <p class="price"> $<%= book.price %> </p>
          <p class="name"> <%= book.name %> </p>
      <% end %>
    </div>
    <% end %>    
  </div>
<% end %>

app/views/books/_form.html.erb
<%= form_for @book, :html => { :class => "form-horizontal book" } do |f| %>

  <% if @book.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @book.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%=f.error_span(:name) %>
  </div>

  <div class="form-group">
    <%= f.label :author, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :author, :class => 'form-control' %>
    </div>
    <%=f.error_span(:author) %>
  </div>
  
  <div class="form-group">
    <%= f.label :price, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :price, :class => 'form-control' %>
    </div>
    <%=f.error_span(:price) %>
  </div>


  <div class="form-group">
    <%= f.label :book_cover, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%=f.file_field :book_cover, :class => 'form-control'  %>
    </div>
    <%=f.error_span(:book_cover) %>   
  </div>

   <div class="form-group">
        <div class="row">
          <div class="col-sm-offset-2 col-sm-8">
            <%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |cb| %>
              <% cb.label(class: "checkbox-inline input_checkbox") {cb.check_box(class: "checkbox") + cb.text} %>
            <% end %>
          </div>
        </div>
   </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                books_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/books/about.html.erb
<h1>Coming...</h1>

app/views/books/contact_us.html.erb
<h1>Coming... </h1>

app/views/books/edit.html.erb
<%- model_class = Book -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/books/explore.html.erb
<h1>Coming..</h1>

app/views/books/index.html.erb
<section class="cd-hero">
    <ul class="cd-hero-slider autoplay">
      <li class="selected">
        <div class="cd-full-width">
          <h2> Rent Book Easily </h2>
          <p>A simple, Freindly way to get books.</p>
          <%= link_to "Explore Now", explore_path, class: 'cd-btn' %>          
        </div> <!-- .cd-full-width -->
      </li>

      <li>
        <div class="cd-half-width">
          <h2> Read more, Learn more  </h2>
          <p>Are you a hungry reader? No need to buy books anymore. Just rent a book from men living beside you</p>
          <a href="#0" class="cd-btn"> know details </a>
          <a href="#0" class="cd-btn secondary"> Finds books now </a>
          

        </div> <!-- .cd-half-width -->        
      </li>

      <li>
    
        <div class="cd-half-width">
          <h2>Save your money</h2>
          <p>Are you a hungry reader? No need to buy books anymore. Just rent a book from men living beside you!</p>
          <a href="#0" class="cd-btn">Start</a>
          <a href="#0" class="cd-btn secondary">Learn More</a>
        </div> <!-- .cd-half-width -->
        
      </li>     
      
    </ul> <!-- .cd-hero-slider -->
  </section> <!-- .cd-hero -->


<%- model_class = Book -%>

<div class="container">
  <section class="featured">
    <h2>Featured books</h2>
    <%= render 'book', obj: @featured_books %>
  </section>

  <section class="recent">
    <h2>Recent books</h2>
    <%= render 'book', obj: @books %>  
  </section>


  <div class="digg_pagination">
    <div align="center page_info">
      <%= will_paginate %>
    </div>  
  </div>
  
</div>



<% if false %>
<% @books.each_slice(3) do | | %>

  <div class="row books_row">
  <% slice.each do |book| %>
    <div class="col-md-4 book"> 
      <%= link_to book_path(book) do %> 
          <div class="cover">
            <%= image_tag book.book_cover %>
          </div>
          <% if book.categories.any? %>
            <p>Categories: <%= render book.categories %> </p>  
          <% end %>
          <p class="price"> $<%= book.price %> </p>
          <p class="name"> <%= book.name %> </p>
      <% end %>
    </div>
    <% end %>    
  </div>
<% end %>



<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:author) %></th>
      <th><%= model_class.human_attribute_name(:price) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= link_to book.id, book_path(book) %></td>
        <td><%= book.name %></td>
        <td><%= book.author %></td>
        <td><%= book.price %></td>
        <td><%=l book.created_at %></td>
        <td>
          <%= link_to t('.show', :default => t("helpers.links.show")),
                      book_path(book), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_book_path(book), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      book_path(book),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_book_path,
            :class => 'btn btn-primary' %>

<% end %>            

app/views/books/new.html.erb
<%- model_class = Book -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/books/new_uploads.html.erb
<h1>Coming...</h1>

app/views/books/show.html.erb
<%- model_class = Book -%>
  
<div class="page-header">
  <h1> <%= @book.name %> </h1>
</div>


<div class="featured">
  <%= image_tag @book.book_cover %>
</div>

<dl class="dl-horizontal">  
  <dt><strong><%= model_class.human_attribute_name(:author) %>:</strong></dt>
  <dd><%= @book.author %></dd>
  <dt><strong><%= model_class.human_attribute_name(:price) %>:</strong></dt>
  <dd><%= @book.price %></dd>
  <% if @book.user %>
  <dt><strong>Contact Info:</strong></dt>
  <dd><%= @book.user.contactinfo %></dd>
  <% end %>
</dl>

<% if @book.categories.any? %>
  <p>Categories: <%= render @book.categories %> </p>  
<% end %>


<%= link_to t('.back', :default => t("helpers.links.back")),
              books_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_book_path(@book), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              book_path(@book),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>

app/views/categories/_category.html.erb
<span class="badge"><%= link_to category.name, category_path(category) %> &nbsp;</span> &nbsp;

app/views/categories/_form.html.erb
<%= form_for(category) do |f| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Categories</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>
<h1 align="center"><%= "Category: " + @category.name %></h1>
<div align="center">
    <div class="row">
      <span class="badge"><%= link_to "Edit Category Name", edit_category_path(@category) %></span>
    </div>

  <%= will_paginate @category_books %>
</div>
<%= render 'books/book', obj: @category_books %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Bookr" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>


    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%#= link_to "Book Rent", root_path, class: 'navbar-brand' %>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">

            <li> <%= link_to root_path, class:'logo' do %>
                   <%= image_tag 'logo.jpg' %> 
                 <% end %>
            </li>

            <li> <%= link_to "Home", root_path %> </li>
            
            <li> <%= link_to "Explore Books", explore_path %> </li>
            
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Categories <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <% Category.all.each do |category| %>
                  <li><%= link_to "#{category.name}", category_path(category) %></li>
              <% end %>
                
              </ul>
            </li>

            <li> <%= link_to "About", about_path %> </li>
            <li> <%= link_to "Contact us", contact_us_path %> </li>
            
                        
          </ul>

          <ul class="nav navbar-nav navbar-right">
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Account <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <% if user_signed_in? %>
                  <li> <%= link_to current_user.username, root_path %> </li>  
                  <li> <%= link_to "Sign out", destroy_user_session_path, method: :delete  %> </li>
                <% else %>
                  <li> <%= link_to "Sign in", new_user_session_path %> </li>
                <% end %>

                
              </ul>
            </li>
          </ul>
        </div>
      </div>
    </div>










<% if false %>
    <div id="myCarousel" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
    <li data-target="#myCarousel" data-slide-to="1"></li>
    <li data-target="#myCarousel" data-slide-to="2"></li>
  </ol>





  <!-- Wrapper for slides -->
  <div class="carousel-inner">
    <div class="item active">
      <%= image_tag 'slider1.jpg' %>      
    </div>

    <div class="item">
      <%= image_tag 'slider2.jpg' %>      
      
    </div>

    <div class="item">
      <%= image_tag 'slider3.png' %>      
    </div>
  </div>



  <!-- Left and right controls -->
  <a class="left carousel-control" href="#myCarousel" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#myCarousel" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
<% end %>



    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>        
      </div><!--/row-->


      <footer>
        <p>&copy; Company 2017</p>
      </footer>

    </div>

  </body>
</html>

app/views/layouts/home.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Bookr" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>


    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%#= link_to "Book Rent", root_path, class: 'navbar-brand' %>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">

            <li> <%= link_to root_path, class:'logo' do %>
                   <%= image_tag 'logo.jpg' %> 
                 <% end %>
            </li>

            <li> <%= link_to "Home", root_path %> </li>
            
            <li> <%= link_to "Explore Books", explore_path %> </li>
            
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Categories <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <% Category.all.each do |category| %>
                  <li><%= link_to "#{category.name}", category_path(category) %></li>
              <% end %>
                
              </ul>
            </li>

            <li> <%= link_to "About", about_path %> </li>
            <li> <%= link_to "Contact us", contact_us_path %> </li>
            
                        
          </ul>

          <ul class="nav navbar-nav navbar-right">
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Account <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <% if user_signed_in? %>
                  <li> <%= link_to current_user.username, root_path %> </li>  
                  <li> <%= link_to "Sign out", destroy_user_session_path, method: :delete  %> </li>
                <% else %>
                  <li> <%= link_to "Sign in", new_user_session_path %> </li>
                <% end %>

                
              </ul>
            </li>
          </ul>
        </div>
      </div>
    </div>










<% if false %>
    <div id="myCarousel" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
    <li data-target="#myCarousel" data-slide-to="1"></li>
    <li data-target="#myCarousel" data-slide-to="2"></li>
  </ol>





  <!-- Wrapper for slides -->
  <div class="carousel-inner">
    <div class="item active">
      <%= image_tag 'slider1.jpg' %>      
    </div>

    <div class="item">
      <%= image_tag 'slider2.jpg' %>      
      
    </div>

    <div class="item">
      <%= image_tag 'slider3.png' %>      
    </div>
  </div>



  <!-- Left and right controls -->
  <a class="left carousel-control" href="#myCarousel" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#myCarousel" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
<% end %>




      <div class="row">
        <div class="col-lg-12">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>        
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2017</p>
      </footer>

    

  </body>
</html>

app/views/users/show.html.erb
<h1 align="center">Welcome to <%= @user.username %>'s page</h1>
<div class="row">
  <div class="col-md-4 col-md-offset-4 center">
    <%= gravatar_for @user, size: 150 %>
  </div>
</div>

<h4 align="center"><%= @user.username %>'s books</h4>
<div class="center">
  <%#= will_paginate @user_books %>
</div>
<%= render 'books/book', obj: @user_books %>
<div class="center">
  <%#= will_paginate @user_books %>
</div>